# Generated by Django 5.1.3 on 2024-11-22 19:50

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_profiles', to='main.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Завантажте вашу фотографію(максимальний розмір 10МБ)', upload_to='images/', validators=[main.models.validate_file_size])),
                ('photo_type', models.CharField(choices=[('GALLERY', 'Gallery Photo'), ('AVATAR', 'Profile Avatar')], default='GALLERY', max_length=10)),
                ('caption', models.CharField(blank=True, help_text='Додайте опис своїй фотографії', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.profile')),
            ],
            options={
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['photo_type'], name='main_profil_photo_t_3625c8_idx'), models.Index(fields=['upload_date'], name='main_profil_upload__e60e09_idx')],
            },
        ),
    ]
