# Generated by Django 4.2.11 on 2024-11-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_profilephoto_profilephotos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePhotos',
            new_name='ProfilePhoto',
        ),
        migrations.RenameIndex(
            model_name='profilephoto',
            new_name='main_profil_photo_t_3625c8_idx',
            old_name='main_profil_photo_t_fd788d_idx',
        ),
        migrations.RenameIndex(
            model_name='profilephoto',
            new_name='main_profil_upload__e60e09_idx',
            old_name='main_profil_upload__5bcc9a_idx',
        ),
    ]
